/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.75).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.tf8.quizapp.controller;

import com.tf8.quizapp.model.dto.ApiError;
import com.tf8.quizapp.model.dto.AuthResponse;
import com.tf8.quizapp.model.dto.User;
import com.tf8.quizapp.model.dto.UserLogin;
import com.tf8.quizapp.model.dto.UserRegister;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;


@Validated
public interface AuthApi {

    @Operation(summary = "Connecter un utilisateur", description = "Authentifie un utilisateur et renvoie un token JWT.", tags={ "Authentification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Connexion réussie.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))),
        
        @ApiResponse(responseCode = "401", description = "Identifiants incorrects.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))) })
    @RequestMapping(value = "/auth/login",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<AuthResponse> authLoginPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody UserLogin body
);


    @Operation(summary = "Inscrire un nouvel utilisateur (Joueur)", description = "Crée un nouveau compte utilisateur avec le rôle JOUEUR.", tags={ "Authentification" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Utilisateur créé avec succès. Renvoie l'objet User.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))),
        
        @ApiResponse(responseCode = "400", description = "Données invalides (ex: email déjà pris).", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ApiError.class))) })
    @RequestMapping(value = "/auth/register",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<User> authRegisterPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody UserRegister body
);

}

