/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.75).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.tf8.quizapp.controller;

import com.tf8.quizapp.model.dto.AuthResponse;
import com.tf8.quizapp.model.dto.UserLogin;
import com.tf8.quizapp.model.dto.UserRegister;
import com.tf8.quizapp.model.dto.UserRequestDTO;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
public interface AuthApi {

	@Operation(summary = "Login")
    @RequestMapping(value = "/auth/login", method = RequestMethod.POST)
    ResponseEntity<?> authLoginPost(@Valid @RequestBody UserLogin body);

    @Operation(summary = "Register")
    @RequestMapping(value = "/auth/register", method = RequestMethod.POST)
    ResponseEntity<?> authRegisterPost(@Valid @RequestBody UserRequestDTO body);

}

