/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.75).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
/*package com.tf8.quizapp.controller;

import com.tf8.quizapp.model.dto.AnswerSubmit;
import com.tf8.quizapp.model.dto.Leaderboard;
import com.tf8.quizapp.model.dto.Question;
import com.tf8.quizapp.model.dto.QuestionDetailed;
import com.tf8.quizapp.model.dto.QuestionLink;
import com.tf8.quizapp.model.dto.Quiz;
import com.tf8.quizapp.model.dto.QuizCreate;
import com.tf8.quizapp.model.dto.QuizDetailed;
import com.tf8.quizapp.model.dto.QuizState;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
public interface QuizApi {

    @Operation(summary = "Lister tous les quiz disponibles", description = "Renvoie une liste de tous les quiz avec leur statut (accessible à tous les rôles).", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Jeu (Joueur)", "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Liste des quiz.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Quiz.class)))) })
    @RequestMapping(value = "/quiz",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Quiz>> quizGet();


    @Operation(summary = "Créer un nouveau quiz (Admin/Animateur)", description = "Crée un nouveau quiz (vide). Réservé aux ADMIN et ANIMATEUR.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Quiz créé. Renvoie le quiz détaillé.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizDetailed.class))),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé (rôle insuffisant).") })
    @RequestMapping(value = "/quiz",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<QuizDetailed> quizPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody QuizCreate body
);


    @Operation(summary = "Terminer un quiz (Admin/Animateur)", description = "Force la fin d'un quiz et passe son statut à 'FINISHED'.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Quiz terminé. Renvoie l'état final.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizState.class))),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé.") })
    @RequestMapping(value = "/quiz/{quizId}/control/finish",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<QuizState> quizQuizIdControlFinishPost(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Passer à l'étape suivante (Admin/Animateur)", description = "Fait avancer le quiz dans son workflow (basé sur le 'step' de la DTO): 1. (Start) -> QUESTION_DISPLAY (Q1) 2. QUESTION_DISPLAY -> RESULTS_DISPLAY (Affiche %) 3. RESULTS_DISPLAY -> ANSWER_DISPLAY (Affiche bonne réponse) 4. ANSWER_DISPLAY -> LEADERBOARD_DISPLAY (Affiche classement) 5. LEADERBOARD_DISPLAY -> QUESTION_DISPLAY (Q2) ... Répète 2-5 ... 6. (Dernière question) -> (État final, voir /finish) ", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "État du quiz mis à jour.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizState.class))),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé."),
        
        @ApiResponse(responseCode = "409", description = "Le quiz n'est pas en cours.") })
    @RequestMapping(value = "/quiz/{quizId}/control/next-step",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<QuizState> quizQuizIdControlNextStepPost(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Lancer un quiz (Admin/Animateur)", description = "Démarre un quiz. Passe son statut à 'RUNNING' et prépare la première question.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Quiz démarré. Renvoie le nouvel état.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizState.class))),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé (rôle insuffisant)."),
        
        @ApiResponse(responseCode = "409", description = "Le quiz est déjà démarré ou terminé.") })
    @RequestMapping(value = "/quiz/{quizId}/control/start",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<QuizState> quizQuizIdControlStartPost(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Supprimer un quiz (Admin/Animateur)", description = "Supprime un quiz et toutes ses questions associées. Réservé aux ADMIN et ANIMATEUR.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Quiz supprimé avec succès."),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé."),
        
        @ApiResponse(responseCode = "404", description = "Quiz non trouvé.") })
    @RequestMapping(value = "/quiz/{quizId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> quizQuizIdDelete(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Obtenir les détails d'un quiz (Admin/Animateur)", description = "Renvoie la structure complète d'un quiz, y compris toutes les questions et les bonnes réponses. Réservé aux ADMIN et ANIMATEUR.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Détails du quiz.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizDetailed.class))),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé."),
        
        @ApiResponse(responseCode = "404", description = "Quiz non trouvé.") })
    @RequestMapping(value = "/quiz/{quizId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<QuizDetailed> quizQuizIdGet(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Soumettre une réponse (Joueur)", description = "Permet au joueur de soumettre son choix pour la question en cours. Doit être appelé avant la fin du temps imparti.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Jeu (Joueur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Réponse acceptée et enregistrée. Le résultat (bonne/mauvaise) sera donné plus tard."),
        
        @ApiResponse(responseCode = "403", description = "Temps écoulé ou réponse déjà soumise."),
        
        @ApiResponse(responseCode = "409", description = "Ce n'est pas le moment de répondre.") })
    @RequestMapping(value = "/quiz/{quizId}/play/answer",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> quizQuizIdPlayAnswerPost(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody AnswerSubmit body
);


    @Operation(summary = "Obtenir la question active (Joueur)", description = "Renvoie la question actuellement affichée (sans la bonne réponse). Ne fonctionne que si l'état est 'QUESTION_DISPLAY'.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Jeu (Joueur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Détails de la question actuelle.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Question.class))),
        
        @ApiResponse(responseCode = "404", description = "Quiz ou question non trouvé."),
        
        @ApiResponse(responseCode = "409", description = "Ce n'est pas le moment d'afficher la question (ex: on affiche les réponses).") })
    @RequestMapping(value = "/quiz/{quizId}/play/current-question",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Question> quizQuizIdPlayCurrentQuestionGet(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Consulter le classement (Joueur)", description = "Renvoie le classement Top 10 pour ce quiz.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Jeu (Joueur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Classement actuel.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Leaderboard.class))),
        
        @ApiResponse(responseCode = "404", description = "Quiz non trouvé.") })
    @RequestMapping(value = "/quiz/{quizId}/play/leaderboard",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Leaderboard> quizQuizIdPlayLeaderboardGet(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Obtenir l'état actuel du jeu (Joueur)", description = "Permet au client joueur de savoir où en est le quiz (quelle question, quelle étape). C'est le point de 'polling' principal si WebSocket échoue.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Jeu (Joueur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "État actuel du jeu.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizState.class))),
        
        @ApiResponse(responseCode = "404", description = "Quiz non trouvé."),
        
        @ApiResponse(responseCode = "409", description = "Le quiz n'est pas encore démarré.") })
    @RequestMapping(value = "/quiz/{quizId}/play/state",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<QuizState> quizQuizIdPlayStateGet(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Mettre à jour un quiz (Admin/Animateur)", description = "Met à jour le titre d'un quiz. Réservé aux ADMIN et ANIMATEUR.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Quiz mis à jour.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizDetailed.class))),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé."),
        
        @ApiResponse(responseCode = "404", description = "Quiz non trouvé.") })
    @RequestMapping(value = "/quiz/{quizId}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<QuizDetailed> quizQuizIdPut(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody QuizCreate body
);


    @Operation(summary = "Lister les questions d'un quiz", description = "Récupère la liste de toutes les questions associées à ce quiz.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Liste des questions du quiz.", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = QuestionDetailed.class)))),
        
        @ApiResponse(responseCode = "404", description = "Quiz non trouvé.") })
    @RequestMapping(value = "/quiz/{quizId}/questions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<QuestionDetailed>> quizQuizIdQuestionsGet(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);


    @Operation(summary = "Lier une question existante à un quiz", description = "Associe une question de la banque (par son ID) à ce quiz.", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Question liée avec succès. Renvoie le quiz mis à jour.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = QuizDetailed.class))),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé."),
        
        @ApiResponse(responseCode = "404", description = "Quiz ou question non trouvé.") })
    @RequestMapping(value = "/quiz/{quizId}/questions",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<QuizDetailed> quizQuizIdQuestionsPost(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody QuestionLink body
);


    @Operation(summary = "Délier une question d'un quiz", description = "Retire la question de ce quiz (ne la supprime pas de la banque centrale).", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Gestion des Quiz (Admin/Animateur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Question déliée avec succès."),
        
        @ApiResponse(responseCode = "403", description = "Accès refusé."),
        
        @ApiResponse(responseCode = "404", description = "Quiz ou question non trouvé.") })
    @RequestMapping(value = "/quiz/{quizId}/questions/{questionId}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> quizQuizIdQuestionsQuestionIdDelete(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
, @Parameter(in = ParameterIn.PATH, description = "ID unique de la question.", required=true, schema=@Schema()) @PathVariable("questionId") Long questionId
);

}*/

