/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.75).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.tf8.quizapp.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;

@Validated
public interface WsApi {

    @Operation(summary = "Établir la connexion WebSocket pour le jeu", description = "Établit une connexion WebSocket pour recevoir les événements de jeu en temps réel. Ceci n'est PAS un endpoint REST. Il utilise le protocole `ws://` ou `wss://`.  **Protocole de Message (documenté séparément - voir AsyncAPI):** - **Client -> Serveur:**   - `answerSubmit` (payload: AnswerSubmit) - **Serveur -> Client:**   - `questionDisplay` (payload: Question)   - `resultsDisplay` (payload: {...})   - `answerDisplay` (payload: AnswerResult)   - `leaderboardDisplay` (payload: Leaderboard)    ", security = {
        @SecurityRequirement(name = "bearerAuth")    }, tags={ "Jeu (Joueur)" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "101", description = "Connexion WebSocket établie (Switching Protocols)."),
        
        @ApiResponse(responseCode = "400", description = "Handshake invalide ou quizId manquant.") })
    @RequestMapping(value = "/ws/quiz/{quizId}",
        method = RequestMethod.GET)
    ResponseEntity<Void> wsQuizQuizIdGet(@Parameter(in = ParameterIn.PATH, description = "ID unique du quiz.", required=true, schema=@Schema()) @PathVariable("quizId") Long quizId
);

}

